version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo # imagen oficial de mongo
    expose:
      - '27017'
    ports:
      - '27017:27017'
  app: 
    container_name: pruebas-node
    restart: always
    build: .
    ports:
      - '3000:3000' # puerto en mi pc : puerto en el contenedor
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on: # para que mi app se conecte con el servicio de la base de datos
      - mongo